src/com/$2012/entity/order/Message.java
package com.$2012.entity.order;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/*
 * 客服留言
 */
@Entity
public class Message {
	private Integer msgId;
	/* 留言内容 */
	private String content;
	/* 留言时间 */
	private Date createDate = new Date();
	/* 留言的员工 */
	private String empName;
	/* 所属订单 */
	private Order order;
	
	public Message() {}
	
	public Message(String content, String empName, Order order) {
		this.content = content;
		this.empName = empName;
		this.order = order;
	}
	@Id @GeneratedValue
	public Integer getMsgId() {
		return msgId;
	}
	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}
	@Column(length=100,nullable=false)
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	@Temporal(TemporalType.TIMESTAMP) @Column(nullable=false)
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(length=20,nullable=false)
	public String getEmpName() {
		return empName;
	}
	public void setEmpName(String empName) {
		this.empName = empName;
	}
	@ManyToOne(optional=false)
	@JoinColumn(name="orderId")
	public Order getOrder() {
		return order;
	}
	public void setOrder(Order order) {
		this.order = order;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((msgId == null) ? 0 : msgId.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Message other = (Message) obj;
		if (msgId == null) {
			if (other.msgId != null)
				return false;
		} else if (!msgId.equals(other.msgId))
			return false;
		return true;
	}
	
}

src/com/$2012/vo/PageContext.java
package com.$2012.vo;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/*
 * 分页（包装类）
 */
@Component("pageCtx")
@Scope("prototype")
public class PageContext<T> {
	/** 页码开始索引和结束索引 **/
	private PageList pageList;
	/** 页码数量 **/
	private int pageListSize = 10;
	/** 总页数 **/
	private long totalPages = 1;
	/** 每页显示记录数 **/
	private int maxResults = 12;
	/** 分页数据 **/
	private List<T> records;
	/** 总记录数 **/
	private long totalRecords;
	/** 当前页码 **/
	private int currentPage = 1;
	
	public PageContext() {}
	
	public PageContext(int maxResults, int currentPage) {
		this.maxResults = maxResults;
		this.currentPage = currentPage;
	}
	
	public PageContext(int pageListSize, int maxResults, int currentPage) {
		this(maxResults, currentPage);
		this.pageListSize = pageListSize;
	}
		
	
	/** 要获取记录的开始索引 **/
	public int getFirstResult() {
		return (this.currentPage-1)*this.maxResults;
	}
	
	public int getPageListSize() {
		return pageListSize;
	}

	public void setPageListSize(int pageListSize) {
		this.pageListSize = pageListSize;
	}

	public void setQueryResult(QueryResult<T> qr){
		setTotalRecords(qr.getTotalRecords());
		setRecords(qr.getResultList());
	}
	
	public long getTotalRecords() {
		return totalRecords;
	}
	public void setTotalRecords(long totalRecords) {
		this.totalRecords = totalRecords;
		setTotalPages(this.totalRecords%this.maxResults==0? this.totalRecords/this.maxResults : this.totalRecords/this.maxResults+1);
	}
	public List<T> getRecords() {
		return records;
	}
	public void setRecords(List<T> records) {
		this.records = records;
	}
	public PageList getPageList() {
		return pageList;
	}
	@Resource
	public void setPageList(PageList pageList) {
		this.pageList = PageList.getPageList(pageListSize, currentPage, totalPages);
	}
	public long getTotalPages() {
		return totalPages;
	}
	public void setTotalPages(long totalPages) {
		this.totalPages = totalPages;
		this.setPageList(pageList);
	}
	public int getMaxResults() {
		return maxResults;
	}
	public int getCurrentPage() {
		return currentPage;
	}
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}

	public int getPrePage() {
		if (currentPage == 1) return 0;
		return currentPage - 1;
	}

	public int getNextPage() {
		if (currentPage >= totalPages) return 0;
		return currentPage + 1;
	}
}

WebContent/page/share/Foot.jsp
<%@ page pageEncoding="gbk"%>
<center>
	<div class="publish_page_bottom" align="center">
	  <table class="b_middle">
	  <tr>
		<td width="104" class="title width_1 t2"><h2>我的帐户</h2></td>
		<td width="104" class="title"><h2>如何付款</h2></td>
		<td width="125" class="title"><h2>配送及运费</h2></td>
		<td width="102" class="title"><h2>办理退换货</h2></td>
		<td width="88" class="title width_2 t3"><h2>帮助中心</h2></td>
	  </tr>
	  <tr>
		<td class="width_1"><a href="#" target="_blank">我的帐户自助服务</a></td>
		<td><a href="#" target="_blank">货到付款常见问题</a></td>
		<td><a href="#" target="_blank">配送范围时间及费用</a></td>
		<td><a href="#" target="_blank">退换货原则</a></td>
		<td class="width_2"><a href="#" target="_blank">找回密码</a></td>
	  </tr>
	  <tr>
		<td class="width_1"><a href="#" target="_blank">如何修改订单</a></td>
		<td><a href="#" target="_blank">网上支付常见问题</a></td>
		<td><a href="#" target="_blank">海外订单的运费</a></td>
		<td><a href="#" target="_blank">退换货流程</a></td>
		<td class="bj_no"></td>
	  </tr>
	  <tr>
		<td class="width_1"><a href="#" target="_blank">如何取消订单</a></td>
		<td><a href="#" target="_blank">邮局汇款常见问题</a></td>
		<td><a href="#" target="_blank">免运费优惠</a></td>
		<td class="bj_no">&nbsp;</td>
		<td class="bj_no"></td>
	  </tr>
	  <tr>
		<td class="bj_no"></td>
		<td><a href="#" target="_blank">银行电汇常见问题</a></td>
		<td class="bj_no">&nbsp;</td>
		<td class="bj_no">&nbsp;</td>
		<td class="bj_no"></td>
	  </tr>
	  <tr>
		<td class="bj_no">&nbsp;</td>
		<td><a href="#" target="_blank">汇款单招领</a></td>
		<td class="bj_no">&nbsp;</td>
		<td class="bj_no">&nbsp;</td>
		<td class="bj_no">&nbsp;</td>
	  </tr>
	</table>
	</div>

	<div class="publish_bottom_message">
	<ul>
		<li><a href="#">公司简介</a></li>
		<li><a href="#">诚征英才</a></li>
		<li><a href="#">网站联盟</a></li>
		<li><a href="#">供货商合作</a></li>
		<li class="m_right"><a href="#">交易条款</a></li>
	</ul>
	</div>
	<div  align="center"  style="MARGIN: 10px 0px 10px 0px;clear:both">Copyright (C) 有才网 2012, All Rights Reserved
		<img src="/images/validate.bmp" border="0" align="middle"/>
		<a href="#" target="_blank" style="color: blue;">京ICP证041189号</a>

	</div>
	</center>

WebContent/page/share/Head.jsp
<%@ page pageEncoding="gbk"%>
<%@include file="/page/share/taglib.jsp" %>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript">
<!--
$(function(){
  if('${type.typeId}'=='') {
    $("#index").css("background", "pink");
  }else{
    $("#t${type.typeId}").css("background", "pink");
    $("#index").css("background", "");
  }
})

function EnterPress(e){ //传入 event 
  var e = e || window.event; 
  if(e.keyCode == 13){ 
    document.forms[0].submit(); 
  } 
} 
//-->
</script>
<div id="Head">
  <div id="HeadTop">
    <div id="Logo"><a href="/" target=_top><img alt=中国最大、最安全的图书网上交易平台！ src="/images/global/yc.jpg" border=0 /></a> </div>
    <div id="HeadNavBar">
      <ul>
        <li class="NoSep"><a id="MyBuyCar"  href="/shopping/cart/list" ><font color="blue"><Strong>购物车</Strong></font></a> </li>
        <li><a href="/page/user/front/register.jsp?toUI=${param.toUI }" >新用户注册</a> </li>
        <li><a href="/page/user/front/login.jsp">用户登录</a> </li>
         <c:if test="${!empty sessionScope.user}"> <li><a href="/front/user/logout" >退出</a> </li></c:if>
        <li><a href="/page/shopping/myOrder.jsp">我的订单</a>服务热线：222-88888888 </li>
      </ul>
    </div>
  </div>
  <div id="ChannelMenu">
	<UL id="ChannelMenuItems">
		<LI id="MenuHome"><a href="/index.jsp"><span id="index">首页</span></a></LI>
		<LI id="ProducType1Home"><a href="/front/product/list?type.typeId=1"><span id="t1">${application.type1 }</span></a></LI>
		<LI id="ProducType1Home"><a href="/front/product/list?type.typeId=2"><span id="t2">${application.type2 }</span></a></LI>
		<LI id="ProducType3Home"><a href="/front/product/list?type.typeId=3"><span id="t3">${application.type3 }</span></a></LI>
		<LI id="ProducType8Home"><a href="/front/product/list?type.typeId=4"><span id="t4">${application.type4 }</span></a></LI>
	</UL>
<!--  SearchBox -->
<div id="SearchBox">
	  <div id="SearchBoxTop">
		  <div id="SearchForm">
			<form action="/front/product/search" method="post" name="search" id="search">
			 <span class="name">商品搜索: </span><input id="word" name="word" value="${word }" onkeypress="EnterPress(event)" onkeydown="EnterPress()" accesskey="s" size="100" maxlength="100"/>
			 <input type="submit" value="搜 索" id="DoSearch"/>
			</form>
		  </div>
	  </div>
      <div id="HotKeywords">
			<ul>
				<li><span>您好<c:if test="${!empty sessionScope.user}"><b>${sessionScope.user.name }</b></c:if>，欢迎来到有才网！</span></li>
			</ul>
      </div>
   </div>
</div><!-- End SearchBox -->
</div>
<!-- Head End -->

WebContent/page/share/fenye.jsp
<%@ page pageEncoding="gbk"%>
<!-- 仿优酷评论分页1---分页特点：当前页码总是位于页面列表的中间
     总记录数：80条 | 每页显示：8条 | 总页数：10  1 2 3 4 5 6 7 8 9 10 -->
<font color="#FFFFFF">
总记录数:${pageCtx.totalRecords}条 | 每页显示:${pageCtx.maxResults}条 | 总页数:${pageCtx.totalPages}页</font>　
<c:forEach begin="${pageCtx.pageList.startPage}" end="${pageCtx.pageList.endPage}" var="p">
    <c:if test="${pageCtx.currentPage==p}"><b><font color="#FFFFFF">${p} </font></b></c:if>
    <c:if test="${pageCtx.currentPage!=p}"><a href="javascript:toPage('${p}')" class="a03">[${p}] </a></c:if>
</c:forEach>

WebContent/page/share/fenye2.jsp
<%@ page pageEncoding="gbk"%>
<!-- 仿优酷评论分页2
     1...2 3 4 5 6...80 上一页 下一页 -->
<c:if test="${pageCtx.pageList.endPage > pageCtx.pageListSize}"><a href="javascript:toPage('1')">[1]</a>...</c:if>
<c:forEach begin="${pageCtx.pageList.startPage}" end="${pageCtx.pageList.endPage}" var="p">
  <c:if test="${pageCtx.currentPage==p}"><b>${p}</b></c:if>
  <c:if test="${pageCtx.currentPage!=p}"><a href="javascript:toPage('${p}')">[${p}]</a></c:if>&nbsp;
</c:forEach>
<c:if test="${pageCtx.pageList.endPage < pageCtx.totalPages}">...<a href="javascript:toPage('${pageCtx.totalPages }')">[${pageCtx.totalPages }]</a></c:if>
<c:if test="${pageCtx.prePage!=0}"><a href="javascript:toPage('${pageCtx.prePage}')">&nbsp;上一页</a></c:if>
<c:if test="${pageCtx.nextPage!=0}"><a href="javascript:toPage('${pageCtx.nextPage}')">&nbsp;下一页</a></c:if>

WebContent/page/share/simpleHead.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>
<div id="Head">
  <div id="HeadTop">
    <div id="Logo"><a href="/" target=_top><img alt="中国最大、最安全的户外用品、体育用品网上交易平台！" src="/images/global/yc.jpg" border=0 /></a> </div>
    <div id="HeadNavBar">
      <ul>
        <li class="NoSep"><a id="MyBuyCar"  href="/shopping/cart/list" ><font color="blue"><Strong>购物车</Strong></font></a> </li>
        <li><a href="/page/user/front/register.jsp?toUI=${param.toUI }" >新用户注册</a> </li>
        <li><a href="/page/user/front/login.jsp">用户登录</a> </li>
        <c:if test="${!empty sessionScope.user}"> <li><a href="/front/user/logout" >退出</a> </li></c:if>
        <li><a href="/page/shopping/myOrder.jsp">我的订单</a> </li>
        <li class="phone">服务热线：222-88888888</li>
      </ul>
    </div>
  </div>
</div>
<!-- Head End -->

WebContent/page/share/taglib.jsp
<%@ taglib uri="/struts-tags" prefix="s" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ taglib uri="http://www.youcai.com/yc" prefix="yc"%>
<%@ taglib uri="http://java.fckeditor.net" prefix="FCK" %>
<%@ taglib uri="http://www.opensymphony.com/oscache" prefix="oscache" %>

WebContent/page/share/uploadSizeError.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<html>
  <head>
    <title>upload</title>
  </head>
  <body>
	<form action="upload.action" method="post" enctype="multipart/form-data">
	  上传错误：文件过大
	</form>
  </body>
</html>

WebContent/page/share/uploadTypeError.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<html>
  <head>
    <title>upload</title>
  </head>
  <body>
	<form action="upload.action" method="post" enctype="multipart/form-data">
	  上传错误：请检查文件类型
	</form>
  </body>
</html>