src/com/$2012/entity/order/PaymentWay.java
package com.$2012.entity.order;
/**
 * 支付方式
 */
public enum PaymentWay {
	/** 网上支付 */
	NET{
		public String getName(){return "网上支付";}
	},
	/** 货到付款 */
	COD{
		public String getName(){return "货到付款";}
	},
	/** 银行电汇 */
	BANKREMITTANCE{
		public String getName(){return "银行电汇";}
	},
	/** 邮局汇款 */
	POSTOFFICEREMITTANCE{
		public String getName(){return "邮局汇款";}
	};
	public abstract String getName();
}

src/com/$2012/entity/product/Product.java
package com.$2012.entity.product;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.compass.annotations.Index;
import org.compass.annotations.Searchable;
import org.compass.annotations.SearchableComponent;
import org.compass.annotations.SearchableId;
import org.compass.annotations.SearchableProperty;

/*
 * 产品（书）
 */
@Entity 
@Searchable
public class Product implements java.io.Serializable {
	private static final long serialVersionUID = 6038809104006738452L;
	private Integer productId;
	/*货号*/
	private String code;
	/*产品名称*/
	private String name;
	/*产品类型*/
	private ProductType type;
	/*底价*/
	private Float basePrice;
	/*市场价*/
	private Float marketPrice;
	/*销售价*/
	private Float salePrice;
	/*简介*/
	private String description;
	/*简介(去掉html标签)*/
	private String description2;
	/*购买说明*/
	private String buyExplain;
	/*是否可见*/
	private Boolean visible = true;
	/*上架日期*/
	private Date showDate = new Date();
	/*销售数量*/
	private Integer saleCount = 0;//根据已收货订单统计
	/*人气指数-本项目中指点击购买的次数*/
	private Long clickCount = 0L;
	/*是否推荐*/
	private Boolean commend = false;
	/*产品样式*/
	private Set<ProductStyle> styles = new HashSet<ProductStyle>();
	/*品牌*/
	private Brand brand;
	
	@Id @GeneratedValue 
	@SearchableId
	public Integer getProductId() {
		return productId;
	}
	public void setProductId(Integer productId) {
		this.productId = productId;
	}
	@Column(length=30)
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}                                                      
	@Column(length=50,nullable=false) 
	@SearchableProperty(index=Index.ANALYZED, boost=2, name="productName")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,optional=false)
	@JoinColumn(name="typeId")//在关系维护端设外键
	@SearchableComponent
	public ProductType getType() {
		return type;
	}
	public void setType(ProductType type) {
		this.type = type;
	}
	@Column(nullable=false)
	public Float getBasePrice() {
		return basePrice;
	}
	public void setBasePrice(Float basePrice) {
		this.basePrice = basePrice;
	}
	@Column(nullable=false) 
	@SearchableProperty(index=Index.NO)
	public Float getMarketPrice() {
		return marketPrice;
	}
	public void setMarketPrice(Float marketPrice) {
		this.marketPrice = marketPrice;
	}
	@Column(nullable=false) 
	@SearchableProperty(index=Index.NO)
	public Float getSalePrice() {
		return salePrice;
	}
	public void setSalePrice(Float salePrice) {
		this.salePrice = salePrice;
	}
	@Transient
	public Float getSavedPrice() {
		return this.marketPrice - this.salePrice;
	}
	@Lob @Column(nullable=false)  
	@SearchableProperty
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	@Column(length=30) 
	@SearchableProperty(index=Index.NO)
	public String getBuyExplain() {
		return buyExplain;
	}
	public void setBuyExplain(String buyExplain) {
		this.buyExplain = buyExplain;
	}
	@Column(nullable=false)
	@SearchableProperty(index=Index.NO)
	public Boolean getVisible() {
		return visible;
	}
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}
	@Temporal(TemporalType.DATE)
	public Date getShowDate() {
		return showDate;
	}
	public void setShowDate(Date showDate) {
		this.showDate = showDate;
	}
	@Column(nullable=false)
	public Integer getSaleCount() {
		return saleCount;
	}
	public void setSaleCount(Integer saleCount) {
		this.saleCount = saleCount;
	}
	@Column(nullable=false)
	public Long getClickCount() {
		return clickCount;
	}
	public void setClickCount(Long clickCount) {
		this.clickCount = clickCount;
	}
	@Column(nullable=false)
	public Boolean getCommend() {
		return commend;
	}
	public void setCommend(Boolean commend) {
		this.commend = commend;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productId == null) ? 0 : productId.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Product other = (Product) obj;
		if (productId == null) {
			if (other.productId != null)
				return false;
		} else if (!productId.equals(other.productId))
			return false;
		return true;
	}
	@OneToMany(cascade=CascadeType.ALL,mappedBy="product")
	@OrderBy("visible desc, styleId asc")
	@SearchableComponent
	public Set<ProductStyle> getStyles() {
		return styles;
	}
	public void setStyles(Set<ProductStyle> styles) {
		this.styles = styles;
	}
	/*
	 * 添加样式
	 */
	public void addStyle(ProductStyle style) {
		if (!this.styles.contains(style)) {
			style.setProduct(this);
			this.styles.add(style);
		}
	}
	/*
	 * 删除样式
	 */
	public void removeStyle(ProductStyle style) {
		if (this.styles.contains(style)) {
			style.setProduct(null);
			this.styles.remove(style);
		}
	}
	@Transient
	public String getDescription2() {
		return description2;
	}
	public void setDescription2(String description2) {
		this.description2 = description2;
	}
	@ManyToOne(cascade=CascadeType.REFRESH)//实际中很多产品未标明品牌
	@JoinColumn(name="brandId")
	@SearchableComponent
	public Brand getBrand() {
		return brand;
	}
	public void setBrand(Brand brand) {
		this.brand = brand;
	}
}

src/com/$2012/vo/Cart.java
package com.$2012.vo;

import java.util.ArrayList;
import java.util.List;

import com.$2012.entity.order.Acceptor;
import com.$2012.entity.order.Buyer;
import com.$2012.entity.order.PaymentWay;

/*
 * 购物车
 */
public class Cart {
	/*购买项*/
	private List<BuyItem> items = new ArrayList<BuyItem>();
	
	/*收货人*/
	private Acceptor acceptor;
	/*购买人*/
	private Buyer buyer; 
	/*购买人是否也是收货人*/
	private String buyerIsAcceptor;
	/*支付方式*/
	private PaymentWay paymentWay;
	/*配送费*/
	private float deliverFee = 10f;
	/*订单附言*/
	private String note;
	
	/*
	 * 添加购物项
	 */
	public void addItem(BuyItem item) {
		if (!items.contains(item)) {
			items.add(item);
		} else {
			for (BuyItem bi : items) {
				if (bi.equals(item)) {
					bi.setAmount(bi.getAmount() + 1);
					break;
				}
			}
		}
	}
	
	/*
	 * 清空购物车
	 */
	public void clear() {
		items.clear();
	}
	
	/*
	 * 删除购物项
	 */
	public void deleteItem(BuyItem item) {
		if (items.contains(item)) items.remove(item);
	}
	

	public List<BuyItem> getItems() {
		return items;
	}

	public void setItems(List<BuyItem> items) {
		this.items = items;
	}

	/*
	 * 计算商品的总金额
	 */
	public float getTotalSalePrice(){
		float result = 0f;
		for(BuyItem item : items){
			result += item.getProduct().getSalePrice() * item.getAmount();
		}
		return result;
	}
	
	/*
	 * 计算商品的总节省金额
	 */
	public float getTotalSavedPrice(){
		float result = 0f;
		for(BuyItem item : items){
			result += item.getProduct().getMarketPrice() * item.getAmount();
		}
		return result - getTotalSalePrice();
	}
	
	/*
	 * 计算订单总金额
	 */
	public float getOrderTotalPrice() {
		return this.getTotalSalePrice() + this.getDeliverFee();
	}

	public String getBuyerIsAcceptor() {
		return buyerIsAcceptor;
	}

	public void setBuyerIsAcceptor(String buyerIsAcceptor) {
		this.buyerIsAcceptor = buyerIsAcceptor;
	}

	public Acceptor getAcceptor() {
		return acceptor;
	}

	public void setAcceptor(Acceptor acceptor) {
		this.acceptor = acceptor;
	}

	public Buyer getBuyer() {
		return buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	public PaymentWay getPaymentWay() {
		return paymentWay;
	}

	public void setPaymentWay(PaymentWay paymentWay) {
		this.paymentWay = paymentWay;
	}

	public float getDeliverFee() {
		return deliverFee;
	}

	public void setDeliverFee(float deliverFee) {
		this.deliverFee = deliverFee;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}

src/com/$2012/web/action/shopping/CartAction.java
package com.$2012.web.action.shopping;


import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.struts2.ServletActionContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.$2012.entity.product.Product;
import com.$2012.entity.product.ProductStyle;
import com.$2012.service.product.ProductService;
import com.$2012.utils.WebUtils;
import com.$2012.vo.BuyItem;
import com.$2012.vo.Cart;
import com.$2012.web.listener.SiteSessionListener;
import com.opensymphony.xwork2.ActionSupport;

@Component
@Scope("prototype")
public class CartAction extends ActionSupport {
	private static final long serialVersionUID = -2034553708522363350L;
	private Cart cart;
	private Integer productId;
	private Integer styleId;
	private ProductService productService;
	
	private String directUrl;
	private String note;
	
	/*
	 * 显示购物车
	 */
	public String list() {
		findCart();
		if (cart == null) return "noCart";
		return SUCCESS;
	}
	
	/*
	 * 找车
	 */
	private void findCart() {
		HttpServletRequest request = ServletActionContext.getRequest();
		cart = WebUtils.getCart(request);
		if (cart == null) {//1.session存在但找不到
			String sid = WebUtils.getCookieByName(request, "cartId");
			if (sid != null) {
				HttpSession session = SiteSessionListener.getSession(sid);
				if (session != null) {
					cart = (Cart) session.getAttribute("cart");
					if (cart != null) {
						SiteSessionListener.removeSession(sid);
						request.getSession().setAttribute("cart", cart);
						WebUtils.addCookie(ServletActionContext.getResponse(), "cartId", request.getSession().getId(), request.getSession().getMaxInactiveInterval());
					}
				}
			}
		}
	}
	
	/*
	 * 购买，加入购物车
	 */
	public String buy() {
		findCart();
		if (cart == null) {//2.session不存在
			HttpServletRequest request = ServletActionContext.getRequest();
			cart = new Cart();
			request.getSession().setAttribute("cart", cart);
			//将sessionid存入cookie中，以便浏览器关掉重启后仍能找到session
			WebUtils.addCookie(ServletActionContext.getResponse(), "cartId", request.getSession().getId(), request.getSession().getMaxInactiveInterval());
		}
		
		if (productId != null && productId > 0) {
			Product product = this.productService.find(productId);
			if (product != null) {
				ProductStyle currentStyle = null;
				if (styleId == null) currentStyle = product.getStyles().iterator().next();
				else {
					for (ProductStyle style : product.getStyles()) {
						if (style.getVisible() && style.getStyleId().equals(styleId)) {
							currentStyle = style;
						}
					}
				}
				product.getStyles().clear();
				if (currentStyle != null) product.addStyle(currentStyle);
				
				cart.addItem(new BuyItem(product, 1));
				
				this.productService.updateClickCount(productId);
			}
		}
		
		return SUCCESS;
	}
	
	/*
	 * 删除购物项
	 */
	public String delete() {
		HttpServletRequest request = ServletActionContext.getRequest();
		cart = WebUtils.getCart(request);
		if (cart != null) {
			Product product = new Product();
			product.setProductId(productId);
			ProductStyle style = new ProductStyle();
			style.setStyleId(styleId);
			product.addStyle(style);
			cart.deleteItem(new BuyItem(product));
		}
		return SUCCESS;
	}
	
	/*
	 * 清空购物车
	 */
	public String clear() {
		HttpServletRequest request = ServletActionContext.getRequest();
		WebUtils.deleteCart(request);//删除购物车
		/*cart = WebUtils.getCart(request);
		if (cart != null) cart.clear();*/
		return SUCCESS;
	}
	
	/*
	 * 更新购买数量
	 */
	public String updateAmount() {
		setAmount();
		return SUCCESS;
	}
	
	/*
	 * 结算
	 */
	public String settleAccounts() {
		setAmount();//结算前更新数量
		//没做到订单确提交确认模块时下面的语句不必看；
		if (directUrl != null && !"".equals(directUrl)) {
			HttpServletRequest request = ServletActionContext.getRequest();
			cart = WebUtils.getCart(request);
			if (cart != null) cart.setNote(note);
			return "toOrderConfirmUI";
		} 
		return SUCCESS;
	}
	
	public void setAmount() {
		HttpServletRequest request = ServletActionContext.getRequest();
		cart = WebUtils.getCart(request);
		if (cart != null) {
			for (BuyItem item : cart.getItems()) {
				StringBuilder key = new StringBuilder("amount_");
				Product product = item.getProduct();
				key.append(product.getProductId()).append("_");
				if (product.getStyles().size() > 0) {
					key.append(product.getStyles().iterator().next().getStyleId());
				}
				String amountStr = request.getParameter(key.toString());
				if (amountStr != null && !"".equals(amountStr)) {
					try {
						int amount = Integer.parseInt(amountStr);
						if (amount > 0) item.setAmount(amount);
					} catch (RuntimeException e) {}
				}
			}
		}
	}
	
	public Cart getCart() {
		return cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getStyleId() {
		return styleId;
	}

	public void setStyleId(Integer styleId) {
		this.styleId = styleId;
	}

	public ProductService getProductService() {
		return productService;
	}
	@Resource
	public void setProductService(ProductService productService) {
		this.productService = productService;
	}

	public String getDirectUrl() {
		return directUrl;
	}

	public void setDirectUrl(String directUrl) {
		this.directUrl = directUrl;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}

WebContent/page/shopping/cart.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>有才网-购物车</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
	<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
<!--
/** 获取以指定字符串为前缀的输入字段集合 **/
/** 数字输入格式是否正确(长度1-4位，第一个数字必须是1-9) **/
function numericFormat(strNumber){   
  var newPar=/^[1-9]\d{0,3}$/;
  return newPar.test(strNumber);
} 

function getInputsByname(name, etype){//
	var inputs = document.getElementsByTagName("input");
	var texts = new Array();
	var y = 0;
	for (var i = 0; i < inputs.length; i++) {
	  if (inputs[i].type == etype && inputs[i].name!=null && inputs[i].name.substring(0, name.length) == name) {
			texts[y] = inputs[i];
			y++;
		}
	}
	return texts;
}
function settleAccounts(){
	if(validateAmount()){		
		var form = document.forms["buycart"];
		form.action="/customer/shopping/cart/settleAccounts";
		form.submit();
	}
}

function modifyAmount(){
	if(validateAmount()){		
		var form = document.forms["buycart"];
		form.action="/shopping/cart/updateAmount";
		form.submit();
	}
}

/** 验证购买数量字段 **/
function validateAmount(){
	var amounts = getInputsByname("amount_", "text");
	if(amounts.length==0){
		alert("您还没有购买商品");
		return false;
	}else{
		for (var i = 0; i < amounts.length; i++) {
			var amount = amounts[i];
			if(amount.value==null || amount.value.trim()==""){
				alert("\n您购买的商品中,有的商品购买数量为空,请填写购买数量");
				amount.focus();
				return false;
			}else if(amount.value=="0"){
				alert("\n您购买的商品中,有的商品购买数量为0,如果您不需要该商品,可以删除它");
				amount.select();
				return false;
			}else if(!numericFormat(amount.value)){
				alert("\n购买数量含有非数字数据,请更正");
				amount.select();
				return false;
			}
		}
	}
	return true;
}
//-->
</SCRIPT>
  </head>
  
  <body onload='$("#index").css("background", "");'>
    <jsp:include page="/page/share/Head.jsp"/>
<BR>
<TABLE cellSpacing=0 cellPadding=5 width="98%" border="0" align="center">
  <TR>
    <TD><TABLE cellSpacing=0 cellPadding=0 width="96%" border=0>
      <TBODY>
        <TR>
          <TD width="58%">&nbsp;</TD>
          <TD width="14%" align="left"><a href="/shopping/cart/clear"><img style="CURSOR:hand;" alt="清空购物车" src="/images/buy/az-empty-shoppingcard.gif" border="0"></a></TD>
          <TD width="15%" align=left><a href="/front/product/list?type.typeId=2"><img src="/images/buy/as-s-continus.gif" width="116" height="22" border="0"></a></TD>
          <TD width="13%" align=right><img style="cursor:hand;" src="/images/buy/az-by-split.gif" width="116" height="22" onClick="javascript:settleAccounts()"/></TD>
        </TR>
      </TBODY>
    </TABLE></TD>
  </TR>

  <TR>
    <TD><FORM id="buycart" name="buycart" action="" method="post">
    <input type="hidden" name="directUrl" value="${param.directUrl }" />
    <input type="hidden" name="note" value="${param.note }" />
    <TABLE cellSpacing=0 cellPadding=6 width="100%" border=0> 
      <TR bgColor=#d7ebff>
        <TD width="457"><STRONG>我的购物车里的商品--马上购买</STRONG></TD>
        <TD width=112><DIV align=center><STRONG>市场价</STRONG></DIV></TD>
        <TD width=181><DIV align=center><STRONG>价格</STRONG></DIV></TD>
        <TD width=73><DIV align=right><STRONG>数量</STRONG></DIV></TD>
        <TD width=66>&nbsp;</TD>
      </TR>
<!-- loop begin -->
<c:forEach items="${sessionScope.cart.items}" var="item"> 
       <TR vAlign="top">
        <TD><STRONG><A href="/front/product/detailShow?productId=${item.product.productId }" target="_blank">${item.product.name}</A></STRONG> <span class="h3color"><c:forEach items="${item.product.styles}" var="style">[颜色：${style.name}]</c:forEach></span><BR><BR></TD>
        <TD width="112" align="center"><SPAN class="price" title="￥${item.product.marketPrice}元"><FONT color="black"><S><B>￥${item.product.marketPrice}元</B></S></FONT></SPAN></TD>
        <TD width="181"><P align="center"><SPAN class="price"><B>￥${item.product.salePrice} 元</B></SPAN> <BR>
          为您节省：<SPAN class=price>￥${item.product.savedPrice}元 </SPAN><BR> </P></TD>
        <TD align="center" width="73"><INPUT type="text" style="WIDTH: 30px" maxLength="3" value="${item.amount}"  name="amount_${item.product.productId}_<c:forEach items='${item.product.styles}' var='style'>${style.styleId}</c:forEach>" onkeypress="javascript:InputIntNumberCheck()" onblur="modifyAmount();"></TD>
        <TD width="66"><a href="/shopping/cart/delete?typeId=${param.typeId }&productId=${item.product.productId}&styleId=<c:forEach items="${item.product.styles}" var="style">${style.styleId}</c:forEach>&directUrl=${param.directUrl }"><img height="17" src="/images/buy/delete.gif" width="45" border="0"></a></TD>
      </TR>
      <TR vAlign="top">
        <TD colSpan="5"><IMG height=1 src="/images/buy/green-pixel.gif" width="100%" border="0"></TD>
      </TR>
</c:forEach>
<!-- loop end -->	  
    </TABLE>
    </FORM>
      <table width="96%" border="0" align="left">
        <tr>
          <td width="60%" align="right">&nbsp;</td>
          <td width="9%" align="right"><DIV align="right"><SPAN class="price"><STRONG><B><FONT color="black">共计:</FONT></B></STRONG></SPAN></DIV></td>
          <td width="11%" align="right"><DIV align="center"><SPAN class="price"><STRONG><B class="price"><FONT color="black">${cart.totalSalePrice } 元</FONT></B></STRONG></SPAN></DIV></td>
          <td width="8%" align="right"><DIV align="right"><SPAN class="price"><STRONG><B><FONT color="black">节省:</FONT></B></STRONG></SPAN></DIV></td>
          <td width="12%" align="right"><DIV align="center"><SPAN class="price"><STRONG><B class="price">${cart.totalSavedPrice } 元</B></STRONG></SPAN></DIV></td>
        </tr>
        <tr>
          <td colspan="3" align="right">&nbsp;</td>
          <td colspan="2" align="right"><img style="CURSOR:hand;" src="/images/buy/az-by-split.gif" width="116" height="22" onClick="javascript:settleAccounts()"></td>
        </tr>
      </table></TD>
  </TR>
</TABLE>
<br>
<jsp:include page="/page/share/Foot.jsp" />
  </body>
</html>

WebContent/page/shopping/finish_bankRemittance.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>有才网-订单完成</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>

  </head>
  
  <body onload='$("#index").css("background", "");'>
    <jsp:include page="/page/share/Head.jsp"/>
<BR>
<h1>订单号:${order.orderId },应付金额:${order.payableFee }元</h1>
<br>
你选择的付款方式为"银行电汇",汇款信息如下:
<br/>
收款人:沈红喜<br>
开户银行:建设银行<br>
账号:02929292929292<br>去<a href="/page/shopping/myOrder.jsp">我的账户</a>查看订单明细<br>
<jsp:include page="/page/share/Foot.jsp" />
  </body>
</html>

WebContent/page/shopping/finish_cod.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>有才网-订单完成</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>

  </head>
  
  <body onload='$("#index").css("background", "");'>
    <jsp:include page="/page/share/Head.jsp"/>
<BR>
<h1>订单号:${order.orderId },应付金额:${order.payableFee }元</h1>
<br>
你选择的付款方式为"货到付款",在未收到商品的这段时间,请保持你的电话畅通.
<br>去<a href="/page/shopping/myOrder.jsp">我的账户</a>查看订单明细<br/>
<jsp:include page="/page/share/Foot.jsp" />
  </body>
</html>

WebContent/page/shopping/finish_net.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>有才网-订单完成</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>

  </head>
  
  <body onload='$("#index").css("background", "");'>
    <jsp:include page="/page/share/Head.jsp"/>
<BR>
<h1>订单号:${order.orderId }${param.orderId },应付金额:${order.payableFee }${param.payableFee }元</h1>
<br>
你选择的付款方式为"网上支付",现在你就可以进行<a href="#"><font color="red">网上支付</font></a>.
<br>去<a href="/page/shopping/myOrder.jsp">我的账户</a>查看订单明细<br/>
<jsp:include page="/page/share/Foot.jsp" />
  </body>
</html>

WebContent/page/shopping/finish_postoFficeRemittance.jsp
<%@ page pageEncoding="gbk"%>
<%@ include file="/page/share/taglib.jsp" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>有才网-订单完成</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>

  </head>
  
  <body onload='$("#index").css("background", "");'>
    <jsp:include page="/page/share/Head.jsp"/>
<BR>
<h1>订单号:${order.orderId },应付金额:${order.payableFee }元</h1>
<br>
你选择的付款方式为"邮局汇款",在汇款单上务必写上您的订单号.如下是汇款信息:<br>
收款人:沈红喜
<br>地址:北京市朝阳区左家庄
<br>去<a href="/page/shopping/myOrder.jsp">我的账户</a>查看订单明细<br/>
<jsp:include page="/page/share/Foot.jsp" />
  </body>
</html>